#!/bin/bash
#PBS -q knlq
#PBS -l select=1:ncpus=2:ngpus=0
#PBS -l walltime=10:00:00
#PBS -o ./data/reports/$PBS_JOBID.out

## Some commands to quickly try this on ISAMBARD
# qsub scripts/isambard.pbs     # Submit the script to Isambard
# qstat -u br-rnzoyem           # Monitor my jobs

## Steps for interactive run on GPU
# 1. qsub -I -q ampereq -l select=1:ncpus=16:ngpus=1 -l walltime=4:00:00
# 2. cd Projects/InverseProblemVnet
# 4. Enjoy !

./build/transfer src/config/test.cfg
